@startuml
class "Vehicle" <<block>> {
  +weight: float
  +speed: float
}
class "Bike" <<block>> {
  attr:Type
}
class "Car" <<block>> {
  +brand: String
  +model: String
}
Bike *-- Car : composition
Car --|> Vehicle : Generalization
@enduml